buildDir: ./build

processors:
  pre:
    - \CodeDocs\Processor\CreateFilesFromTopics
  post:
    - \My\SomeProcessor:
        foo: bar

finalizers:
  - \CodeDocs\Finalizer\CopyExportFiles:
      dest: ./some/dir
      purge: true

sources:
  - baseDir: .
    docsDir: ./docs
    classDirs:
      - ./classes

params:
  someKey: someValue
  someNumber: 123

annotationNamespaces:
  My\Annotation: /path/to/annotations

markupNamespaces:
  - My\Markup

plugins:
  - \My\Plugin
  - \My\Other\Plugin:
      paramKey: paramVal
      foo: bar
